<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/04/06 03:56:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=myPOS',
  'username' => 'root',
  'password' => 'tara',
  'name' => 'doctrine',
)),);
